feat : merge feat Post
INSPJT/instagram_clone_backend pull request #25
Opened 2021-03-05 10:24 UTC by AndoneKwon

## Description

게시물 생성, 게시물 한개 조회, 게시물 삭제 로직 및 테스트 코드 작성

## Changes

- 기본 브랜치에서 Users로 작성되어 있던 부분 모두 수정

2021-03-05 10:27 UTC, heonilp approved these changes

2021-03-05 10:29 UTC, goodGid commented on src/main/java/our/yurivongella/instagramclone/controller/PostApi.java
> +    @PostMapping("")
```suggestion
    @PostMapping
```

2021-03-05 10:52 UTC, goodGid commented on src/main/java/our/yurivongella/instagramclone/controller/PostApi.java
> +        return new ResponseEntity<>(id + "인 포스트가 만들어졌습니다.", HttpStatus.OK);
```suggestion
return ResponseEntity.ok(T)
```

``` java
	public static <T> ResponseEntity<T> ok(T body) {
		return ok().body(body);
	}
```

이렇게 해도 되지 않을까용??

2021-03-05 10:57 UTC, goodGid commented on src/main/java/our/yurivongella/instagramclone/service/PostService.java
> +        post.getPictureURLs().addAll(list);
@AndoneKwon 님
이렇게 하면 
영속성 컨텍스트에서 
Dirty Check 들어가면서

Transaction Commit 할 때
실제로 DB에 반영 될 거 같은데 
의도한게 맞나용?? 

@adamdoha 위 질문대로 동작하는거 맞는지 체크좀 ㅎㅎ

2021-03-05 10:58 UTC, goodGid commented on src/main/java/our/yurivongella/instagramclone/service/PostService.java
> +    @Transactional
@AndoneKwon 님
이거 안붙혀도 
repostiory 내부적으로
@Transactional 있어서 굳이 필요없어보이는데

이거 없으면 안동작하나용?? 
(몰라서 물어봅니다 ㅋㅋㅋ)

2021-03-05 11:00 UTC, goodGid commented on src/main/java/our/yurivongella/instagramclone/service/PostService.java
> +            return null;
``` java
post.ifPresentOrElse(i -> {
            PostReadResponseDto.toPostResponseDto(i, member);
        }, null);
```

이런식으로도 되지 않나 싶군요 ㅎㅎ
( 정상적으로 동작하는지는 저도 몰라요 ! )
( 그냥 이렇게 가능하지 않을까 싶어서 ㅎㅎ )

2021-03-05 14:11 UTC, ParkJiwoon commented on src/main/java/our/yurivongella/instagramclone/service/PostService.java
> +    public Long testCreate(PostCreateRequestDto postCreateRequestDto, Long userId) {
`testCreate` 는 아직 인증로직 없어서 추가한건가요?

2021-03-05 14:14 UTC, ParkJiwoon commented on src/main/java/our/yurivongella/instagramclone/service/PostService.java
> +    public Long testCreate(PostCreateRequestDto postCreateRequestDto, Long userId) {
만약 그런거면 `// TODO: deleted` 같은걸로 표시해두는게 확실할 것 같습니다

2021-03-05 14:57 UTC, AndoneKwon commented on src/main/java/our/yurivongella/instagramclone/service/PostService.java
> +            return null;
Dto 객체를 리턴해야해서 저렇게 작성하면 동작을 하지 않네요..ㅎㅎ.. 중괄호 추가하였습니다.

2021-03-05 14:59 UTC, ParkJiwoon commented on src/main/java/our/yurivongella/instagramclone/service/PostService.java
> +            return null;
값이 없을 때 `null` 값을 리턴하는 것보다 Exception 을 던지는게 더 명확할 것 같습니다.
이거는 논의 필요

2021-03-05 15:02 UTC, AndoneKwon commented on src/main/java/our/yurivongella/instagramclone/service/PostService.java
> +    @Transactional
제가 알기로는 Transaction을 안써주면 프록시에만 저장되고 실제로 데이터베이스에 커밋이 되지 않는걸로 알고있어서 붙였습니다. 제가 이전에 저걸 안붙여서 update가 진행이 안됐던 적이 있거든요..

2021-03-05 15:03 UTC, AndoneKwon commented on src/main/java/our/yurivongella/instagramclone/service/PostService.java
> +    public Long testCreate(PostCreateRequestDto postCreateRequestDto, Long userId) {
네 TODO 주석 추가하였습니다.

2021-03-05 16:07 UTC, adamdoha requested changes
Reviewing

2021-03-05 16:07 UTC, adamdoha commented on src/main/java/our/yurivongella/instagramclone/domain/post/Post.java
>      @OneToMany(mappedBy = "post")
post가 삭제되면 사진리스트도 같이 삭제되도록 Cascade를 걸어주는 것도 좋을 것 같습니다.
구현상으로도 더 명확하고 그냥 생각해봐도 합리적이지 않나요?

2021-03-05 16:07 UTC, adamdoha commented on src/main/java/our/yurivongella/instagramclone/service/PostService.java
> +        post.getPictureURLs().addAll(list);
post는 영속화 대상입니다.

그리고 postCreateRequestDto.toPictureURLs(post)는 List<PictureUrl>을 가져옵니다.
즉, Post Entity의 Collection을 가져오는데, saveAPI로 pictureURLRepository를 이용하여 saveAll을 하는 것은 이상해보이진 않는데요.

컬렉션은 Dirty Check 대상이 아닙니다.

2021-03-05 16:10 UTC, ParkJiwoon commented on src/main/java/our/yurivongella/instagramclone/service/PostService.java
> +    public Long create(PostCreateRequestDto postCreateRequestDto, Member member) {
MemberId 를 SecurityContext 에 담아서 전역으로 불러쓸수 있습니다.
일단 테스트용으로 한것같은데 Member 쪽 머지되면 develop 땡겨서 하시면 될것같아요

2021-03-05 18:41 UTC, ParkJiwoon commented on src/main/java/our/yurivongella/instagramclone/service/PostService.java
> +    public Long testCreate(PostCreateRequestDto postCreateRequestDto, Long userId) {
수정했습니다 [15b2410](https://github.com/INSPJT/instagram_clone_backend/pull/25/commits/15b2410a6e9d2535a4fa8d077fc12f900e2d6f97)

2021-03-05 19:58 UTC, adamdoha commented on src/main/java/our/yurivongella/instagramclone/service/PostService.java
> +    @Transactional
단건 insert 결과 말씀하신 것 처럼 내부에 Transaction이 걸려 있어서 서비스 레벨에서 굳이 Transaction을 걸지 않아도 제대로 쿼리가 나가고 커밋이 되고 있네요. 알쏭달쏭하군요.. 서비스 레벨에서 트랜잭션을 걸지 않으면 정상 동작하지 않던 추억들이 있는데 말이죠 ㅋㅋㅋㅋㅋ ㅠ

2021-03-05 20:04 UTC, ParkJiwoon commented on src/main/java/our/yurivongella/instagramclone/service/PostService.java
> +        post.getPictureURLs().addAll(list);
테스트 해보니 DB 까지 정상적으로 들어가는것 확인

2021-03-06 02:37 UTC, adamdoha reviewed
로깅 작업도 추가되면 좋을 것 같네요!

2021-03-06 02:37 UTC, adamdoha commented on src/main/java/our/yurivongella/instagramclone/controller/dto/post/CommentResponseDto.java
> +    LocalDateTime created;
별건 아니지만 접근 지정자가 있으면 더 좋을 것 같네요.

2021-03-06 02:37 UTC, adamdoha commented on src/main/java/our/yurivongella/instagramclone/controller/dto/post/MemberDto.java
> +    public static MemberDto toMemberDto(Member otherUser, Member user) {
여기도 네이밍 반영해주시면 좋을 것 같아요.

2021-03-06 02:37 UTC, adamdoha commented on src/main/java/our/yurivongella/instagramclone/controller/dto/post/MemberDto.java
> +                .pictureUrl(null)
없어도 동일한 의미겠네요

2021-03-06 02:37 UTC, adamdoha commented on src/main/java/our/yurivongella/instagramclone/controller/dto/post/PostCreateRequestDto.java
> +    public List<PictureURL> toPictureURLs(Post post) {
to 보다는 어떤 값들을 추출해서 얻어오는 과정이니 get이나 from이 좋아보입니다.

2021-03-06 02:37 UTC, adamdoha commented on src/main/java/our/yurivongella/instagramclone/controller/dto/post/PostReadResponseDto.java
> +    Long viewCount;
22

2021-03-06 02:37 UTC, adamdoha commented on src/main/java/our/yurivongella/instagramclone/service/PostService.java
> +            //throw new RuntimeException("게시물이 없습니다.");
혹시 .get~.orElse 로는 안되나요?

2021-03-06 02:40 UTC, adamdoha reviewed
수고 많으십니다.

2021-03-06 02:41 UTC, adamdoha approved these changes

2021-03-06 08:33 UTC, ParkJiwoon commented on src/main/java/our/yurivongella/instagramclone/controller/AuthController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(email + " 회원가입이 완료되었습니다.");
이미 수정했으니 반영해도 상관없지만 PR 하나당 한가지 주제의 수정만 존재하는게 좋습니다.
다른 기능에 대한 수정 또는 리팩토링은 별도의 피쳐를 따서 하는게 좋아요

2021-03-06 09:20 UTC, ParkJiwoon commented on src/main/java/our/yurivongella/instagramclone/service/PostService.java
> +        post = postRepository.save(post);
1. `PostController` 에서 `Long id = postService.create(postRequestDto, SecurityUtil.getCurrentMemberId());` 이렇게 호출하고 있는데 `PostService.create` 내부에서 중복해서 `MemberId` 를 호출하고 있어요. 
파라미터로 안받게 수정하면 좋을 것 같습니다.

2. 파라미터로 넘길때 `orElseThrow` 를 넣는건 가독성이 많이 떨어지는 것 같습니다.
`Member` 값을 가져올 때 먼저 처리하면 좋을것 같아요


```suggestion
    public Long create(PostCreateRequestDto postCreateRequestDto) {
        Member member = memberRepository.findById(SecurityUtil.getCurrentMemberId())
                .orElseThrow(() -> new RuntimeException("조회자 정보가 존재하지 않습니다."));

        Post post = postRepository.save(postCreateRequestDto.toPost(member));
```

2021-03-06 09:30 UTC, ParkJiwoon commented on src/main/java/our/yurivongella/instagramclone/service/PostService.java
> +                -> new RuntimeException("게시물이 없습니다.")), member);
위 리뷰와 같은 내용입니다.

```suggestion
        Post post = postRepository.findById(postId)
                .orElseThrow(() -> new RuntimeException("게시물이 없습니다."));

        return PostReadResponseDto.of(post, member);
```

2021-03-06 09:43 UTC, ParkJiwoon commented on src/main/java/our/yurivongella/instagramclone/service/PostService.java
> +        }
위 리뷰와 마찬가지로 `orElseThrow` 를 밖으로 빼는게 좋습니다.
그리고 `post.getId()` 는 **Post 의 ID* 입니다.
`post.getMember().getId()` 를 사용해야 합니다.

```suggestion
        Post post = postRepository.findById(postId)
                .orElseThrow(() -> new RuntimeException("게시물이 없습니다."));

        if (post.getMember().getId().equals(SecurityUtil.getCurrentMemberId())) {
            throw new RuntimeException("게시물 삭제 권한이 없습니다.");
        }
```

2021-03-06 10:03 UTC, ParkJiwoon commented on src/main/java/our/yurivongella/instagramclone/service/PostService.java
> +    @Transactional
새벽에 @adamdoha 와 확인한 내용 정리

- `@Transactional` 을 붙이지 않아도 CRUD 하는데는 문제가 없음.
- 대신 `@Transactional` 이 붙지 않은 메소드에서 에러가 발생해도 데이터 롤백이 안됨
- Service Layer 에서는 여러 상황에 대비해서 안전하게 가기 위해 `@Transactional` 을 관용적으로 붙임

이 메소드에서는 붙이는게 맞다고 생각합니다.
`pictureURLs` saveAll 할 때 에러가 발생하면 이미 저장된 `post` 데이터는 롤백되지 않을 겁니다.

2021-03-06 13:48 UTC, AndoneKwon commented on src/main/java/our/yurivongella/instagramclone/controller/AuthController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(email + " 회원가입이 완료되었습니다.");
넵 다음부터는 한가지의 주제만 수정하도록 하겠습니다!

2021-03-06 13:57 UTC, AndoneKwon commented on src/main/java/our/yurivongella/instagramclone/controller/PostApi.java
> +        return new ResponseEntity<>(id + "인 포스트가 만들어졌습니다.", HttpStatus.OK);
해당사항 반영하여 수정하였습니다.

2021-03-06 13:59 UTC, AndoneKwon commented on src/main/java/our/yurivongella/instagramclone/controller/PostController.java
> +    @DeleteMapping("/{postId}/{userId}")
uri의 userId는 테스트 때문에 임시로 집어넣었습니다.
로직에서 userId가 필요한 이유는 해당 사용자가 아닌데 postId만 알고 있는 상태로 삭제할 가능성이 있어서 토큰에 있는 userId를 이용하여 한번더 검증해 놓습니다.
[70ccdb27edc6182362cc126dc87135044bc99df1]https://github.com/INSPJT/instagram_clone_backend/pull/25/commits/70ccdb27edc6182362cc126dc87135044bc99df1)

2021-03-06 14:04 UTC, AndoneKwon commented on src/main/java/our/yurivongella/instagramclone/controller/dto/post/CommentResponseDto.java
> +    public static CommentResponseDto toCommentResponseDto(Comment comment, Member member) {
해당 사항 모두 반영하였습니다.
https://github.com/INSPJT/instagram_clone_backend/pull/25/commits/035f47c363b548346d2cfdd9aab9cf1d264f3917

2021-03-06 14:07 UTC, AndoneKwon commented on src/main/java/our/yurivongella/instagramclone/service/PostService.java
> +        Post post = postCreateRequestDto.toPosts(member);
해당사항도 수정하였습니다..ㅎㅎ

2021-03-06 14:08 UTC, AndoneKwon commented on src/main/java/our/yurivongella/instagramclone/domain/post/Post.java
>      @OneToMany(mappedBy = "post")
사진리스트에 대한 Cascade를 걸어놓았습니다.
https://github.com/INSPJT/instagram_clone_backend/pull/25/commits/394b8dea9d2632d3b6758a21b90415ded92774c6

2021-03-06 14:09 UTC, AndoneKwon commented on src/main/java/our/yurivongella/instagramclone/controller/dto/post/CommentResponseDto.java
> +    LocalDateTime created;
접근지정자 넣었습니다.
https://github.com/INSPJT/instagram_clone_backend/pull/25/commits/035f47c363b548346d2cfdd9aab9cf1d264f3917

2021-03-06 14:09 UTC, AndoneKwon commented on src/main/java/our/yurivongella/instagramclone/controller/dto/post/MemberDto.java
> +    public static MemberDto toMemberDto(Member otherUser, Member user) {
네이밍 반영하였습니다.
https://github.com/INSPJT/instagram_clone_backend/pull/25/commits/035f47c363b548346d2cfdd9aab9cf1d264f3917

2021-03-06 14:11 UTC, AndoneKwon commented on src/main/java/our/yurivongella/instagramclone/controller/dto/post/PostCreateRequestDto.java
> +    public List<PictureURL> toPictureURLs(Post post) {
get으로 수정하였습니다.
https://github.com/INSPJT/instagram_clone_backend/pull/25/commits/035f47c363b548346d2cfdd9aab9cf1d264f3917

2021-03-06 14:12 UTC, AndoneKwon commented on src/main/java/our/yurivongella/instagramclone/controller/dto/post/PostReadResponseDto.java
> +    Long viewCount;
접근제어자 설정하였습니다.
https://github.com/INSPJT/instagram_clone_backend/pull/25/commits/394b8dea9d2632d3b6758a21b90415ded92774c6

2021-03-06 14:23 UTC, AndoneKwon commented on src/main/java/our/yurivongella/instagramclone/service/PostService.java
> +            //throw new RuntimeException("게시물이 없습니다.");
orElseThrow로 수정하였습니다. 
임시로 Test를 위해 null로 던졌는데 Exception으로 수정하였습니다.
https://github.com/INSPJT/instagram_clone_backend/pull/25/commits/1519df54b1d9b36648e15396918ab756c642a84d

2021-03-06 14:29 UTC, AndoneKwon commented on src/main/java/our/yurivongella/instagramclone/service/PostService.java
> +        post = postRepository.save(post);
반영하여 수정하였습니다.
https://github.com/INSPJT/instagram_clone_backend/pull/25/commits/1519df54b1d9b36648e15396918ab756c642a84d

2021-03-06 14:29 UTC, AndoneKwon commented on src/main/java/our/yurivongella/instagramclone/service/PostService.java
> +        }
반영하여 수정하였습니다.
https://github.com/INSPJT/instagram_clone_backend/pull/25/commits/1519df54b1d9b36648e15396918ab756c642a84d

2021-03-06 14:29 UTC, AndoneKwon commented on src/main/java/our/yurivongella/instagramclone/service/PostService.java
> +                -> new RuntimeException("게시물이 없습니다.")), member);
반영하여 수정하였습니다.
https://github.com/INSPJT/instagram_clone_backend/pull/25/commits/1519df54b1d9b36648e15396918ab756c642a84d

2021-03-06 15:26 UTC, syureu approved these changes
이미 중요한 얘기는 돌파고님과 정중앙님이 다 해주신 관계로 Approve합니다.

2021-03-06 15:51 UTC, AndoneKwon commented on src/main/java/our/yurivongella/instagramclone/service/PostService.java
> +    @Transactional
따라서 해당 사항에 대해서 수정이 없는거 같으니 그대로 가겠습니다.

2021-03-06 15:53 UTC, AndoneKwon commented on src/main/java/our/yurivongella/instagramclone/domain/post/Post.java
> +    public Post(String content, Member member) {
Member 객체가 Post 객체에 필수가 아니라는 것을 깨닫고 두가지 사항을 수정하였습니다.
- Member를 추가하는 로직을 추가로 추가
- Member의 PostList에 Post를 추가하는 로직
https://github.com/INSPJT/instagram_clone_backend/pull/25/commits/41e33f0f75adc46e6e1c6f94102b41d8ea36e616

2021-03-06 15:54 UTC, AndoneKwon commented on src/main/java/our/yurivongella/instagramclone/controller/dto/post/MemberDto.java
> +                .pictureUrl(null)
해당사항 리팩토링 하여 반영하였습니다.
https://github.com/INSPJT/instagram_clone_backend/pull/25/commits/41e33f0f75adc46e6e1c6f94102b41d8ea36e616

2021-03-06 15:57 UTC, merged